name: Commitlint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Run Commitlint
        uses: wagoid/commitlint-github-action@v5
