name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Run Prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --no-error-on-unmatched-pattern .
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Cache Poetry
        id: cache-poetry
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: poetry
      - name: Install Poetry
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: poetry
      - name: Install dependencies
        run: poetry install --with lint
      - name: Typecheck with mypy
        run: poetry run mypy .
  ruff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - check
          - format
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Cache Poetry
        id: cache-poetry
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: poetry
      - name: Install Poetry
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: poetry
      - name: Install dependencies
        run: poetry install --no-root --only lint
      - name: Ruff ${{ matrix.command }}
        run: poetry run ruff ${{ matrix.command }} --diff
